# "org" ensures this Service is used with the correct Serverless Framework License Key.
org: sainath
# "service" is the name of this project. This will also be added to your AWS resource names.
service: backend

stages:
  default:
    params:
      tableName: "users-table-${sls:stage}"

provider:
  name: aws
  region: ap-south-1
  runtime: nodejs20.x
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
  environment:
    USERS_TABLE: ${param:tableName}
    
plugins:
  - serverless-offline

  
custom:
  serverless-offline:
     httpPort: 5050
     lambdaPort: 4002


functions:
  gitWebhook:
    handler: src/handler.gitWebhook
    events:
      - httpApi:
          path: /crb/git-webhook
          method: get
  getAccessToken:
    handler: src/handler.getAccessToken
    events:
      - httpApi:
          path: /crb/get-access-token
          method: get

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tableName}
